# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LineSplitter
                                 A QGIS plugin
 This plugin splits a line by points into many lines
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-02-23
        copyright            : (C) 2022 by Artsiom Sauchuk, CTLup
        email                : artsiom.sauchuk@uniroma1.it
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Artsiom Sauchuk, CTLup'
__date__ = '2022-02-23'
__copyright__ = '(C) 2022 by Artsiom Sauchuk, CTLup'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LineSplitter class from file LineSplitter.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .line_splitter import LineSplitterPlugin
    return LineSplitterPlugin()
